baseURL = 'https://gidroforum.ru'
canonifyURLs = true
languageCode = 'ru'
defaultContentLanguage = "ru"
hasCJKLanguage = true
enableEmoji = true
title = 'ГИДРОФОРУМ'
copyright = 'gidroforum.ru'
theme = ["gidroforum"]
pagerSize = 5
[params]
  defaultCover = '/images/logo_site.png'
  email = 'fsa@armarost.ru'
  phone = '+7 (863) 209-76-96'
  phoneLink = '+78632097696'
  whatsapp = '78632097696'
  adress = 'Россия, Ростов-на-Дону, пер. 1-ый Машиностроительный, 8/1'
  [[params.socialMedia]]
    name = 'ГИДРОФОРУМ'
    url = '/'
  [[params.blogroll]]
    name = 'VK'
    url = 'https://vk.com/'
