name: Update Theme

on:
  workflow_dispatch:
    
jobs:
  update_theme:
    runs-on: ubuntu-latest
    steps:
    - name: Update submodule
      uses: fatjyc/update-submodule-action@v5.0
      with:
        user: floyd-li
        token: ${{ secrets.GH_TOKEN }}
        repo_owner: floyd-li
        repo: hugo-theme-itheme
        committor_username: floyd-li
        committor_email: floyd.li@outlook.com
        path: themes/hugo-theme-itheme
        sync_ref: master
